In [2]:
import pandas as pd

from sklearn.neighbors import LocalOutlierFactor
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.metrics import recall_score

### Carga dos Dados

In [3]:
# Carregar dados
df_churn = pd.read_csv('./datasets/churn_telecom.csv')

In [4]:
# Visualizar a estrutura
df_churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   IDCliente         7032 non-null   object
 1   Genero            7032 non-null   object
 2   Mais65anos        7032 non-null   int64
 3   TemParceiro       7032 non-null   object
 4   TemDependentes    7032 non-null   object
 5   PhoneService      7032 non-null   object
 6   MultipleLines     7032 non-null   object
 7   InternetService   7032 non-null   object
 8   OnlineSecurity    7032 non-null   object
 9   OnlineBackup      7032 non-null   object
 10  DeviceProtection  7032 non-null   object
 11  TechSupport       7032 non-null   object
 12  StreamingTV       7032 non-null   object
 13  StreamingMovies   7032 non-null   object
 14  tenure            7032 non-null   int64
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [5]:
# Visualizar as primeiras linhas do DataFrame
df_churn.head(10)

    IDCliente  Genero  Mais65anos  ... MonthlyCharges TotalCharges Churn
0  7590-VHVEG  Female           0  ...          29.85        29.85    No
1  5575-GNVDE    Male           0  ...          56.95      1889.50    No
2  3668-QPYBK    Male           0  ...          53.85       108.15   Yes
3  7795-CFOCW    Male           0  ...          42.30      1840.75    No
4  9237-HQITU  Female           0  ...          70.70       151.65   Yes
5  9305-CDSKC  Female           0  ...          99.65       820.50   Yes
6  1452-KIOVK    Male           0  ...          89.10      1949.40    No
7  6713-OKOMC  Female           0  ...          29.75       301.90    No
8  7892-POOKP  Female           0  ...         104.80      3046.05   Yes
9  6388-TABGU    Male           0  ...          56.15      3487.95    No

[10 rows x 21 columns]

In [6]:
# Visualizar as ultimas linhas do DataFrame
df_churn.tail(10)

       IDCliente  Genero  Mais65anos  ... MonthlyCharges TotalCharges Churn
7022  9767-FFLEM    Male           0  ...          69.50      2625.25    No
7023  0639-TSIQW  Female           0  ...         102.95      6886.25   Yes
7024  8456-QDAVC    Male           0  ...          78.70      1495.10    No
7025  7750-EYXWZ  Female           0  ...          60.65       743.30    No
7026  2569-WGERO  Female           0  ...          21.15      1419.40    No
7027  6840-RESVB    Male           0  ...          84.80      1990.50    No
7028  2234-XADUH  Female           0  ...         103.20      7362.90    No
7029  4801-JZAZL  Female           0  ...          29.60       346.45    No
7030  8361-LTMKD    Male           1  ...          74.40       306.60   Yes
7031  3186-AJIEK    Male           0  ...         105.65      6844.50    No

[10 rows x 21 columns]

In [7]:
# Contar clientes usando a variável Churn como referência
df_churn['Churn'].value_counts()

Churn
No     5163
Yes    1869
Name: count, dtype: int64

In [8]:
# Distribuição de clientes que saíram percentual
df_churn['Churn'].value_counts(normalize=True)

Churn
No     0.734215
Yes    0.265785
Name: proportion, dtype: float64

### Preparação da Base para Algoritmo LOF

In [10]:
# Selecionando as colunas para o algoritmo
X = df_churn.drop(columns=['IDCliente', 'Churn'])
y = df_churn['Churn']

In [ ]:
# Definir uma função para transformar "Yes" e "No" em 1 e 0
def binary_transform_function(X):
    return X.map(lambda X: 1 if X == 'Yes' else 0)

In [ ]:
# Transformações
numeric_features = ['tenure', 'MonthlyCharges', 'TotalCharges']
categorical_features = ['Genero', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup',
                        'DeviceProtection', 'StreamingTV', 'StreamingMovies', 'Contract',
                        'PaymentMethod']
binary_features = ['TemParceiro', 'TemDependentes', 'TechSupport', 'PhoneService', 'PaperlessBilling']
no_transformation_features = ['Mais65Anos']

# Criar Transformers
numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder()
binary_transformer = FunctionTransformer(binary_transform_function)

# Criar o preprocessor
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features),
        ('bin', binary_transformer, binary_features),
        ('pass', 'passthrough', no_transformation_features)]
)

# Transformar os dados
X_transformed = preprocessor.fit_transform(X)

AttributeError: type object 'numpy.float64' has no attribute 'kind'